dataset_name: cresci-2015
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    data = get_train_data(dataset_name)
  File "/scratch/network/rr4001/projects/voon/TwitterBotBusters/src/GCN_GAT/dataset.py", line 41, in get_train_data
    des_embedding = torch.load(osp.join(path, 'des_tensor.pt'))
  File "/scratch/network/rr4001/projects/voon/envs/botbusters/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/scratch/network/rr4001/projects/voon/envs/botbusters/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/scratch/network/rr4001/projects/voon/envs/botbusters/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../BotRGCN/cresci_15/processed_data/des_tensor.pt'
